require('config.mappings')
require('plugins.paq')
require('config.options')
require('config.gui')
require('plugins.nvim-treesitter')
require('plugins.mini-completions')
require('plugins.lsp-config')
require('plugins.metals')
